[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.exif",
  "php82Extensions.fileinfo",
  "php82Extensions.openssl",
  "php82Extensions.curl",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "composer",
  "nginx"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php-fpm -D && nginx -g 'daemon off;'"
