[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs", "npm", "nginx", "php-fpm"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force"
]

[start]
cmd = "php-fpm -F & nginx -g 'daemon off;'"